# Generated by Django 5.0.3 on 2024-07-14 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_rename_client_negotiation_user_and_more'),
        ('panier', '0003_alter_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='negotiation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.negotiation'),
        ),
    ]
