# Generated by Django 5.0.3 on 2024-07-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0004_cartitem_negotiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
