# Generated by Django 5.0.3 on 2024-07-14 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_rename_client_negotiation_user_and_more'),
        ('panier', '0005_remove_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.produit'),
        ),
    ]
