# Generated by Django 5.0.3 on 2024-07-14 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_remove_negotiation_prixnegocie'),
        ('panier', '0007_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panier.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='negotiation',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.negotiation'),
        ),
    ]
