# Generated by Django 5.0.3 on 2024-07-12 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentifications', '0004_alter_userprofile_user'),
        ('commande', '0005_alter_order_user_alter_orderproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentifications.client'),
        ),
    ]
