# Generated by Django 5.0.3 on 2024-07-14 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_remove_negotiation_prixnegocie'),
        ('commande', '0006_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='negotiation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boutique.negotiation'),
        ),
    ]
