# Generated by Django 5.0.3 on 2024-07-12 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentifications', '0004_alter_userprofile_user'),
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentifications.client'),
        ),
    ]
