# Generated by Django 5.0.3 on 2024-07-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_negotiation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negotiation',
            old_name='client',
            new_name='user',
        ),
        migrations.AddField(
            model_name='negotiation',
            name='PrixUnitaire',
            field=models.FloatField(default=0),
        ),
    ]
