# Generated by Django 5.0.3 on 2024-07-11 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('roles', models.CharField(choices=[('Administrateur', 'Administrateur'), ('Vendeur', 'Vendeur'), ('GestionnaireStock', 'GestionnaireStock'), ('Client', 'Client')], max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Adminitrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(default='/media/Admin/default_profil.png', upload_to='Admin')),
                ('IdUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenoms', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=15)),
                ('ville', models.CharField(max_length=50, null=True)),
                ('telephone', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(default='/media/Client/default_profil.png', upload_to='Client')),
                ('IdUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GesteionnaireStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(default='/media/GesteionnaireStock/default_profil.png', upload_to='GesteionnaireStock')),
                ('IdUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=50, null=True)),
                ('telephone', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(default='/media/Vendeur/default_profil.png', upload_to='Vendeur')),
                ('IdUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
