# Generated by Django 5.0.3 on 2024-07-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieproduit',
            name='cat_image',
            field=models.ImageField(blank=True, upload_to='Categories'),
        ),
    ]
