# Generated by Django 5.0.3 on 2024-07-11 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentifications', '0001_initial'),
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_lu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantiteVendu', models.IntegerField()),
                ('MontantTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DateVente', models.DateTimeField(auto_now_add=True)),
                ('IdClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentifications.client')),
                ('IdProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit')),
                ('IdVendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentifications.vendeur')),
            ],
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('IdVente', models.ManyToManyField(to='myapp.vente')),
            ],
        ),
    ]
