# Generated by Django 5.0.3 on 2024-03-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('roles', models.CharField(choices=[('Administratuer', 'Administratuer'), ('Vendeur', 'Vendeur')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
