# Generated by Django 5.0.3 on 2024-03-26 20:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_client_telephone_alter_client_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adminitrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(default=0, null=True)),
                ('IdUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('PrixUnitaire', models.FloatField()),
                ('Description', models.TextField(null=True)),
                ('IdCategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categorieproduit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantiteStock', models.IntegerField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('IdProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=50, null=True)),
                ('telephone', models.IntegerField(default=0, null=True)),
                ('IdUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantiteVendu', models.IntegerField()),
                ('MontantTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DateVente', models.CharField(max_length=100)),
                ('IdClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('IdProduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
                ('IdVendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vendeur')),
            ],
        ),
    ]
