# Generated by Django 5.0.3 on 2024-03-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_adminitrateur_image_vendeur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminitrateur',
            name='image',
            field=models.ImageField(default='default_profil.png', upload_to='Admin'),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='image',
            field=models.ImageField(default='default_profil.png', upload_to='Vendeur'),
        ),
    ]
