# Generated by Django 5.0.3 on 2024-03-31 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='est_lu',
        ),
    ]
