# Generated by Django 5.0.3 on 2024-04-04 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_created_at_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='roles',
            field=models.CharField(choices=[('Administratuer', 'Administratuer'), ('Vendeur', 'Vendeur'), ('GesteionnaireStock', 'GesteionnaireStock')], max_length=100),
        ),
        migrations.CreateModel(
            name='GesteionnaireStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(default='default_profil.png', upload_to='GesteionnaireStock')),
                ('IdUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
