# Generated by Django 5.0.3 on 2024-04-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_utilisateur_roles_gesteionnairestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='IdProduit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit', unique=True),
        ),
    ]
