# Generated by Django 5.0.3 on 2024-04-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_stock_idproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='IdProduit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit'),
        ),
    ]
