# Generated by Django 5.0.3 on 2024-04-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_vente_datevente'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
