# Generated by Django 5.0.3 on 2024-04-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_recuvente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreation', models.DateTimeField(auto_now_add=True)),
                ('IdVente', models.ManyToManyField(to='myapp.vente')),
            ],
        ),
        migrations.DeleteModel(
            name='RecuVente',
        ),
    ]
